//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTraking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_type { get; set; }
        public string product_brand { get; set; }
        public string product_lable { get; set; }
        public Nullable<int> product_start_inv { get; set; }
        public Nullable<int> product_in_inv { get; set; }
        public Nullable<int> product_min_req { get; set; }
        public Nullable<decimal> product_unit_pr { get; set; }
        public Nullable<decimal> product_sell_pr { get; set; }
    }
}
