//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryTraking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class purchase
    {
        public int Purchase_id { get; set; }
        public Nullable<int> Purchase_pro_id { get; set; }
        public Nullable<System.DateTime> Purchase_date { get; set; }
        public Nullable<int> Purchase_no { get; set; }
        public Nullable<decimal> Purchase_price { get; set; }
        public string Purchase_sup_fname { get; set; }
        public string Purchase_sup_lname { get; set; }
    }
}
